language: php

php:
- 5.6

install:
- composer install

notifications:
  email:
    recipients:
    - ej@creatop.com.tw
    on_success: always
    on_failure: always

script: phpunit Tests